-- Run once in the Supabase SQL editor. Only Netlify's server key can access these tables.
begin;
create table public.store_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
create table public.store_products (
  id bigint generated by default as identity (start with 1000) primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  published boolean not null default false,
  data jsonb not null check (jsonb_typeof(data) = 'object'),
  updated_at timestamptz not null default now()
);
create table public.store_reviews (
  id uuid primary key default gen_random_uuid(),
  product_id bigint not null references public.store_products(id) on delete restrict,
  name text not null check (length(name) between 2 and 80),
  email text not null check (length(email) between 3 and 254),
  rating smallint not null check (rating between 1 and 5),
  message text not null check (length(message) between 10 and 3000),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  moderated_at timestamptz,
  moderated_by uuid references auth.users(id)
);
create index store_reviews_product_status on public.store_reviews(product_id, status, created_at desc);
create table public.store_limits (
  key text primary key,
  started_at timestamptz not null default now(),
  count integer not null default 1
);
create table public.store_audit (
  id bigint generated always as identity primary key,
  actor uuid references auth.users(id),
  action text not null,
  resource text not null,
  created_at timestamptz not null default now()
);
alter table public.store_admins enable row level security;
alter table public.store_products enable row level security;
alter table public.store_reviews enable row level security;
alter table public.store_limits enable row level security;
alter table public.store_audit enable row level security;
revoke all on public.store_admins, public.store_products, public.store_reviews, public.store_limits, public.store_audit from anon, authenticated;
grant all on public.store_admins, public.store_products, public.store_reviews, public.store_limits, public.store_audit to service_role;
grant usage, select on sequence public.store_products_id_seq, public.store_audit_id_seq to service_role;

-- Atomic rate limit works across concurrent serverless instances. No raw IP stored.
create function public.store_take_limit(p_key text, p_limit integer, p_seconds integer)
returns boolean language plpgsql security definer set search_path = '' as $$
declare hits integer;
begin
  delete from public.store_limits where started_at < now() - interval '2 days';
  insert into public.store_limits as limits(key, started_at, count) values(p_key, now(), 1)
  on conflict(key) do update set
    count = case when limits.started_at < now() - make_interval(secs => p_seconds) then 1 else limits.count + 1 end,
    started_at = case when limits.started_at < now() - make_interval(secs => p_seconds) then now() else limits.started_at end
  returning count into hits;
  return hits <= p_limit;
end $$;
revoke all on function public.store_take_limit(text, integer, integer) from public, anon, authenticated;
grant execute on function public.store_take_limit(text, integer, integer) to service_role;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values('product-images', 'product-images', true, 3145728, array['image/webp'])
on conflict(id) do nothing;
-- No storage write policies: uploads go through the authenticated Netlify endpoint.
commit;
